global using Qwirkle.Core.Entities;
global using Qwirkle.Core.Enums;
global using Qwirkle.Core.ExtensionMethods;
global using Qwirkle.Core.Ports;
global using Qwirkle.Core.ValueObjects;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using RackPosition = System.Byte;
global using Abscissa = System.SByte;
global using Ordinate = System.SByte;
