global using Qwirkle.Domain.Entities;
global using Qwirkle.Domain.Enums;
global using Qwirkle.Domain.Ports;
global using Qwirkle.Domain.ValueObjects;
global using System;
global using System.Collections.Generic;
global using System.IO;
global using System.Linq;
global using TorchSharp;
global using static TorchSharp.torch.nn;
global using static TorchSharp.torch.nn.functional;
global using RackPosition = System.Byte;
