global using Qwirkle.Domain.Entities;
global using Qwirkle.Domain.Enums;
global using Qwirkle.Domain.Ports;
global using Qwirkle.Domain.ValueObjects;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading.Tasks;
global using RackPosition = System.Byte;
global using Abscissa = System.SByte;
global using Ordinate = System.SByte;
global using TorchSharp;
global using static TorchSharp.torch;
global using static TorchSharp.torch.nn;
global using static TorchSharp.torch.nn.functional;
